# Generated by Django 5.2.6 on 2025-09-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatisha_kca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('sponsor', 'Sponsor'), ('dean', 'Dean'), ('vc', 'VC'), ('head_of_department', 'Head of department'), ('non_teaching_staff', 'Non-teaching Staff')], max_length=20),
        ),
    ]
