# Generated by Django 3.2.25 on 2025-09-29 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatisha_kca', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('sponsor', 'Sponsor'), ('non_teaching_staff', 'Non-teaching Staff'), ('hod_bsd', 'HoD - BSD'), ('hod_bac', 'HoD - BAC'), ('hod_bbit', 'HoD - BBIT'), ('hod_bit', 'HoD - BIT'), ('dean_sot', 'Dean school of Technology'), ('dean_student', 'Dean of Student'), ('dean_sob', 'Dean school of Business'), ('dean_school_of_education_art', 'Dean School of Education & Art'), ('vc', 'VC')], max_length=200),
        ),
        migrations.CreateModel(
            name='IssueSubmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('bsd', 'Head of Department BSD'), ('bac', 'Head of Department BAC'), ('bbit', 'Head of Department BBIT'), ('bit', 'Head of Department BIT'), ('sot', 'School of Technology'), ('dos', 'Dean of Student'), ('sob', 'School of Business'), ('sea', 'School of education & Art'), ('vc_ceo', 'VC & CEO')], max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('forwarded', 'Forwarded')], default='pending', max_length=20)),
                ('response', models.TextField(blank=True, null=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('moved_to_faq', models.BooleanField(default=False)),
                ('current_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_issues', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForwardingHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('date_forwarded', models.DateTimeField(auto_now_add=True)),
                ('forwarded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_from', to=settings.AUTH_USER_MODEL)),
                ('forwarded_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_to', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwarding_history', to='chatisha_kca.issuesubmissionmodel')),
            ],
        ),
    ]
