# Generated by Django 5.2.6 on 2025-09-18 05:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatisha_kca', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueSubmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('finance', 'Finanace'), ('ict', 'ICT'), ('exam', 'Exam'), ('timetabbling', 'Timetabling'), ('sot', 'SOT'), ('clinic', 'Clinic')], max_length=50)),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('media', 'Media'), ('low', 'Low')], max_length=10)),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('underview', 'Under review'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
