# Generated by Django 5.2.6 on 2025-09-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatisha_kca', '0003_issuesubmissionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuesubmissionmodel',
            name='department',
            field=models.CharField(choices=[('finance', 'Finance'), ('ict', 'ICT'), ('exam', 'Exam'), ('timetabling', 'Timetabling'), ('sot', 'SOT'), ('clinic', 'Clinic')], max_length=50),
        ),
        migrations.AlterField(
            model_name='issuesubmissionmodel',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10),
        ),
        migrations.AlterField(
            model_name='issuesubmissionmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('underview', 'Under Review'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
    ]
