# Generated by Django 3.2.25 on 2025-09-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatisha_kca', '0003_auto_20250929_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuesubmissionmodel',
            name='department',
            field=models.CharField(choices=[('bsd', 'Head of Department BSD'), ('bac', 'Head of Department BAC'), ('bbit', 'Head of Department BBIT'), ('bit', 'Head of Department BIT'), ('sot', 'Dean School of Technology'), ('dos', 'Dean of Students'), ('sob', 'Dean School of Business'), ('sea', 'Dean School of education & Art'), ('vc_ceo', 'VC & CEO')], max_length=255),
        ),
    ]
