# Generated by Django 3.2.25 on 2025-09-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatisha_kca', '0004_alter_issuesubmissionmodel_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('sponsor', 'Sponsor'), ('non_teaching_staff', 'Non-teaching Staff'), ('hod_bsd', 'Head of department BSD'), ('hod_bac', 'Head of Department BAC'), ('hod_bbit', 'Head of Department BBIT'), ('hod_bit', 'Head of Department BIT'), ('dean_sot', 'Dean school of Technology'), ('dean_student', 'Dean of Student'), ('dean_sob', 'Dean school of Business'), ('dean_school_of_education_art', 'Dean School of Education & Art'), ('vc', 'VC')], max_length=200),
        ),
    ]
