# Generated by Django 5.2.6 on 2025-09-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatisha_kca', '0005_alter_issuesubmissionmodel_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('sponsor', 'Sponsor'), ('dean_sot', 'Dean school of Technology'), ('vc', 'VC'), ('head_of_department', 'Head of department'), ('non_teaching_staff', 'Non-teaching Staff'), ('dean_student', 'Dean of Student'), ('dean_sob', 'Dean school of Business'), ('dean_school_of_education_art', 'Dean School of Education & Art')], max_length=200),
        ),
        migrations.AlterField(
            model_name='issuesubmissionmodel',
            name='department',
            field=models.CharField(choices=[('finance', 'Finance'), ('sea', 'School of education & Art'), ('dos', 'Dean of Student'), ('sob', 'Dean School of Business'), ('sot', 'Dean School of Technology'), ('vc', 'VC & CEO'), ('head_of_department', 'Head of Department')], max_length=50),
        ),
    ]
