# Generated by Django 5.2.6 on 2025-09-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatisha_kca', '0006_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuesubmissionmodel',
            name='department',
            field=models.CharField(choices=[('finance', 'Finance'), ('sea', 'School of education & Art'), ('dos', 'Dean of Student'), ('sob', 'School of Business'), ('sot', 'School of Technology'), ('vc', 'VC & CEO'), ('head_of_department', 'Head of Department')], max_length=50),
        ),
    ]
