# Generated by Django 3.2.25 on 2025-09-29 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatisha_kca', '0006_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='created_at',
        ),
    ]
