# Generated by Django 5.2.6 on 2025-09-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatisha_kca', '0007_alter_issuesubmissionmodel_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuesubmissionmodel',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuesubmissionmodel',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issuesubmissionmodel',
            name='department',
            field=models.CharField(choices=[('sea', 'School of education & Art'), ('dos', 'Dean of Student'), ('sob', 'School of Business'), ('sot', 'School of Technology'), ('vc_ceo', 'VC & CEO'), ('head_department', 'Head of Department')], max_length=50),
        ),
        migrations.AlterField(
            model_name='issuesubmissionmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('forwarded', 'Forwarded')], default='pending', max_length=20),
        ),
    ]
