# Generated by Django 5.2.6 on 2025-09-20 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatisha_kca', '0008_issuesubmissionmodel_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuesubmissionmodel',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
