# Generated by Django 5.2.6 on 2025-09-20 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatisha_kca', '0009_issuesubmissionmodel_responded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuesubmissionmodel',
            name='current_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ForwardingHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('date_forwarded', models.DateTimeField(auto_now_add=True)),
                ('forwarded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_from', to=settings.AUTH_USER_MODEL)),
                ('forwarded_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_to', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwarding_history', to='chatisha_kca.issuesubmissionmodel')),
            ],
        ),
    ]
