# Generated by Django 4.2.25 on 2025-10-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatisha_kca', '0010_alter_userprofile_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_image',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', upload_to='avatars/'),
        ),
    ]
