# Generated by Django 5.2.6 on 2025-09-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatisha_kca', '0011_faqmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQModel',
        ),
        migrations.AlterField(
            model_name='issuesubmissionmodel',
            name='department',
            field=models.CharField(choices=[('sea', 'School of education & Art'), ('dos', 'Dean of Student'), ('sob', 'School of Business'), ('sot', 'School of Technology'), ('vc_ceo', 'VC & CEO'), ('head_department', 'Head of Department')], max_length=255),
        ),
        migrations.AlterField(
            model_name='issuesubmissionmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('forwarded', 'Forwarded'), ('faq', 'FAQ')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='issuesubmissionmodel',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
