# Generated by Django 4.2.25 on 2025-10-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatisha_kca', '0012_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='default.png', upload_to='profile_pics/'),
        ),
    ]
