# Generated by Django 5.2.6 on 2025-09-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatisha_kca', '0013_faqmodel_alter_issuesubmissionmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuesubmissionmodel',
            name='moved_to_faq',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='issuesubmissionmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('forwarded', 'Forwarded')], default='pending', max_length=20),
        ),
    ]
