# Generated by Django 4.2.25 on 2025-10-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatisha_kca', '0015_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forwardinghistorymodel',
            name='date_forwarded',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='issuesubmissionmodel',
            name='date_submitted',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='issuesubmissionmodel',
            name='response_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='default.png', upload_to='avatars/'),
        ),
    ]
