# Generated by Django 4.2.25 on 2025-10-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatisha_kca', '0017_alter_notification_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forwardinghistorymodel',
            name='date_forwarded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
