# Generated by Django 4.2.25 on 2025-10-07 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatisha_kca', '0018_alter_forwardinghistorymodel_date_forwarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuesubmissionmodel',
            name='date_submitted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='issuesubmissionmodel',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
