# Generated by Django 4.2.25 on 2025-10-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatisha_kca', '0019_alter_issuesubmissionmodel_date_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqmodel',
            name='date_resolved',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
