# Generated by Django 4.2.25 on 2025-10-10 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatisha_kca', '0020_faqmodel_date_resolved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqmodel',
            name='date_resolved',
        ),
    ]
