# Generated by Django 4.2.25 on 2025-10-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatisha_kca', '0021_remove_faqmodel_date_resolved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forwardinghistorymodel',
            name='note',
            field=models.TextField(default='Reason', max_length=100),
        ),
    ]
