# Generated by Django 4.2.25 on 2025-11-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatisha_kca', '0023_alter_customuser_role_alter_faqmodel_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin_assistant', 'Admin Assistant'), ('faculty_manager', 'Faculty Manager'), ('hod_time_tabling', 'HoD Timetabling'), ('cod_nac', 'CoD NAC'), ('hod_exam_nac', 'HoD Exam NAC'), ('cod_sdis', 'CoD SDIS'), ('hod_exam_sdis', 'HoD Exam SDIS'), ('cod_dsai', 'CoD SDAI'), ('hod_exam_sdai', 'HoD Exam SDAI'), ('hod_student_attachment', 'HoD Student Attachment'), ('hod_projects', 'HoD Projects'), ('dean_sot', 'Dean SOT'), ('dvc_sot', 'DVC'), ('vc', 'VC')], max_length=200),
        ),
    ]
